### ISSUE TITLE
Remove configure and Makefile.in

### ISSUE THREAD

**Issue by olexandr-konovalov** [nzidaric/fsr#14]
The package does not have binaries - do you have plans to have them or make other use of configure-make build process? If not, I suggest to remove them. I've setup a test which tries to clone a repository into a Docker container with the latest GAP stable-4.10 branch and approved packages, and FSR tests fail there (https://travis-ci.org/gap-packages/gap-docker-pkg-tests-stable-4.10-devel/jobs/429243609) because `configure` is not executable - although, if it is not needed, I'd simply remove it...

**Comment by nzidaric** [comment]
thanks
