### ISSUE TITLE
 LaTeX Warnings

### ISSUE THREAD

**Issue by olexandr-konovalov** [nzidaric/fsr#4]
There are some LaTeX warnings displayed while building manuals:
```
#I  LaTeX Warning: Label `RunFSR' multiply defined.
#I  LaTeX Warning: Label `RunFSR' multiply defined.
#I  LaTeX Warning: Label `RunFSR' multiply defined.
#I  LaTeX Warning: Label `LFSR' multiply defined.
#I  LaTeX Warning: Label `LFSR' multiply defined.
#I  LaTeX Warning: Label `LFSR' multiply defined.
#I  LaTeX Warning: Label `NLFSR' multiply defined.
#I  LaTeX Warning: Label `misc' multiply defined.
```
because of same labels reused elsewhere, and 
```
#I  LaTeX Warning: Empty `thebibliography' environment on input line 3.
```
- perhaps because of empty bibliography.

**Comment by nzidaric** [comment]
can only find one ##  <#GAPDoc Label="RunFSR">, i dont understand how it is multiply defined

**Comment by olexandr-konovalov** [comment]
@nzidaric This is because you have
```
##  <Meth Name="RunFSR" Arg='fsr [, ist, num, pr]'/>
##  <Meth Name="RunFSR" Arg='fsr ,elm [, num, pr]'/>
##  <Meth Name="RunFSR" Arg='fsr , ist, elmvec [, pr]'/>
##  <Meth Name="RunFSR" Arg='fsr , z, elmvec [, pr]'/>
```
so these four definitions are not distinguishable. You need either to squeeze them into one
`<Meth Name="RunFSR" Arg='fsr [, someid, someotherid, pr]'/>` where `someid` and `someotherid` are some meaningful identifiers, and explain that the 2nd argument, if bound, is that, the 3rd, if bound, is that, etc. Alternatively, you need to add labels for the 2nd-4th definitions, like
```
##  <Meth Name="RunFSR" Arg='fsr [, ist, num, pr]'/>
##  <Meth Name="RunFSR" Arg='fsr ,elm [, num, pr]' Label="for this and that"/>
##  <Meth Name="RunFSR" Arg='fsr , ist, elmvec [, pr]' Label="for another case" />
##  <Meth Name="RunFSR" Arg='fsr , z, elmvec [, pr]' Label="for something different" />
```

**Comment by nzidaric** [comment]
thanks, that worked
i was certain only ##  <#GAPDoc Label="RunFSR"> matters

brn
